version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresMetabase
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: ${POST_USER} 
      POSTGRES_PASSWORD: ${POST_PASS}
      POSTGRES_DB: ${POST_DB}
    ports:
      - "5439:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./pg/set_metabase_env.sql:/docker-entrypoint-initdb.d/set_metabase_env.sql
  
  metabase:
    container_name: metabase
    restart: always
    image: metabase/metabase:latest
    depends_on: 
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    ports:
      - 3000:3000   
volumes:
  postgres_db:


